#ifndef THREAD_DEFS_HPP

#define MOCAP_THREAD_HZ 120
#define MOCAP_THREAD_TOUT 2
#define MOCAP_THREAD_TYPE FIFO
#define MOCAP_THREAD_PRI 90

#define VPE_THREAD_HZ 35
#define VPE_THREAD_TOUT 2
#define VPE_THREAD_TYPE FIFO
#define VPE_THREAD_PRI 99

#define READ_THREAD_HZ 40
#define READ_THREAD_TOUT 2
#define READ_THREAD_TYPE OTHER
#define READ_THREAD_PRI 0

#define WRITE_THREAD_HZ 4
#define WRITE_THREAD_TOUT 2
#define WRITE_THREAD_TYPE OTHER
#define WRITE_THREAD_PRI 0

#define PRINTF_THREAD_HZ 20
#define PRINTF_THREAD_TOUT 2
#define PRINTF_THREAD_TYPE OTHER
#define PRINTF_THREAD_PRI 0

#endif // !THREAD_DEFS_HPP