#pragma once

// #define HIGHSPEED

#ifdef HIGHSPEED
#define MOCAP_THREAD_HZ 300
#define MOCAP_THREAD_TOUT 2
#define MOCAP_THREAD_TYPE FIFO
#define MOCAP_THREAD_PRI 99

#define VPE_THREAD_HZ 40
#define VPE_THREAD_TOUT 2
#define VPE_THREAD_TYPE FIFO
#define VPE_THREAD_PRI 98

#define READ_THREAD_HZ 500E3
#define READ_THREAD_TOUT 2
#define READ_THREAD_TYPE FIFO
#define READ_THREAD_PRI 90

#define RELAY_THREAD_HZ 500E3
#define RELAY_THREAD_TOUT 2
#define RELAY_THREAD_TYPE FIFO
#define RELAY_THREAD_PRI 89

#define WRITE_THREAD_HZ 100
#define WRITE_THREAD_TOUT 2
#define WRITE_THREAD_TYPE FIFO
#define WRITE_THREAD_PRI 92

#define PRINTF_THREAD_HZ 20
#define PRINTF_THREAD_TOUT 2
#define PRINTF_THREAD_TYPE OTHER
#define PRINTF_THREAD_PRI 0

#define NONBLOCK_IO_THREAD_HZ 120
#define NONBLOCK_IO_THREAD_TOUT 2
#define NONBLOCK_IO_THREAD_TYPE FIFO
#define NONBLOCK_IO_THREAD_PRI 30

#define SYS_THREAD_HZ 1
#define SYS_THREAD_TOUT 2
#define SYS_THREAD_TYPE FIFO
#define SYS_THREAD_PRI 80

#else
#define MOCAP_THREAD_HZ 300
#define MOCAP_THREAD_TOUT 2
#define MOCAP_THREAD_TYPE FIFO
#define MOCAP_THREAD_PRI 99

#define VPE_THREAD_HZ 40
#define VPE_THREAD_TOUT 2
#define VPE_THREAD_TYPE FIFO
#define VPE_THREAD_PRI 98

#define READ_THREAD_HZ 900
#define READ_THREAD_TOUT 2
#define READ_THREAD_TYPE FIFO
#define READ_THREAD_PRI 90

#define RELAY_THREAD_HZ 900
#define RELAY_THREAD_TOUT 2
#define RELAY_THREAD_TYPE FIFO
#define RELAY_THREAD_PRI 89

#define WRITE_THREAD_HZ 100
#define WRITE_THREAD_TOUT 2
#define WRITE_THREAD_TYPE FIFO
#define WRITE_THREAD_PRI 92

#define PRINTF_THREAD_HZ 30
#define PRINTF_THREAD_TOUT 2
#define PRINTF_THREAD_TYPE OTHER
#define PRINTF_THREAD_PRI 0

#define NONBLOCK_IO_THREAD_HZ 30
#define NONBLOCK_IO_THREAD_TOUT 2
#define NONBLOCK_IO_THREAD_TYPE FIFO
#define NONBLOCK_IO_THREAD_PRI 30

#define SYS_THREAD_HZ 1
#define SYS_THREAD_TOUT 2
#define SYS_THREAD_TYPE FIFO
#define SYS_THREAD_PRI 80

#endif